name: 'Install ODI Scenaroios Action'
description: 'Installs the scenarios contained in the RITM directory.'
inputs:
  RITM:
    description: "The name of the RITM to be deployed"
    required: true
  odiUrl:
    description: "The JDBC URL of the target ODI repository"
    required: true
  odiSchema: 
    description: "The schema of the target ODI repository"
    required: true
  odiSchemaPwd: 
    description: "The password used for connecting to the schema of the target ODI repository"
    required: true
  odiWorkRepository:
    description: "The name of the target ODI work repository"
    required: true
  odiUsername:
    description: "The username used in order to connect to the ODI instance"
    required: true
  odiUserPwd:
    description: "The password of the user used to connect to the ODI instance"
    required: true
  key:
    description: "The key to be used to import encrypted ODI scenarios"
    required: false

runs:
  using: "composite" 
  steps:
    - name: Make executeable
      run: chmod +x ${{ github.action_path }}/installOdiScenarios.sh
      shell: bash
    - id: install-scenarios
      run: |
        odiSchema=$(echo "${{ inputs.odiSchema }}" | tr -d "\n")
        ${{ github.action_path }}/installOdiScenarios.sh ${{ inputs.RITM }} ${{ inputs.odiUrl }} ${odiSchema} ${{ inputs.odiSchemaPwd }} ${{ inputs.odiWorkRepository }} ${{ inputs.odiUsername }} ${{ inputs.odiUserPwd }} '${{ inputs.key }}'
      shell: bash
