name: 'Generate Liquibase Changelog'
description: 'Generates a liquibase changelog file for sql scripts in RITM'
inputs:
  RITM:
    description: "The name of the RITM to be deployed"
    required: true
  environment:
    description: "The environment to deploy to"
    required: true
  changelog-file: 
    description: "The user provided changelog file name (if any)"
outputs:
  changelogFilePath:
    description: "The path to the generated changelog file"
    value: ${{steps.liquibase-changelog-generator.outputs.changelogFilePath}}
    
runs:
  using: "composite" 
  steps:
    - id: liquibase-changelog-generator
      run: ${{ github.action_path }}/generateChangeLog.sh ${{ inputs.RITM }} ${{ inputs.environment }} ${{ inputs.changelog-file }}
      shell: bash
      
