name: 'Generate Liquibase Changelog'
description: 'Generates a liquibase changelog file for sql scripts in RITM'
inputs:
  RITM:  # id of input
    description: 'The name of the RITM to be deployed'
    required: true
  environment:
    description: 'The environment to deploy to'
 outputs:
  changelogFilePath:
    description: 'The path to the generated changelog file'
    value: ${{ steps.liquibase-changelog-generator.outputs.changelogFilePath }}
runs:
  using: "composite" 
  steps:
    - id: liquibase-changelog-generator
      run: /Users/matteofoiadelli/Documents/Development/LiquibaseChangeLogGenerator/generateChangeLog.sh ${{ inputs.RITM }} ${{ inputs.environment }}
      shell: bash
      
