name: 'Generate Liquibase Changelog'
description: 'Generates a liquibase changelog file for sql scripts in RITM'
inputs:
  RITM:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
runs:
  using: "composite" 
  steps:
    - id: liquibase-changelog-generator
      run: /Users/matteofoiadelli/Documents/Development/LiquibaseChangeLogGenerator/generateChangeLog.sh ${{ inputs.RITM }}
      shell: bash
      
