name: 'Hello World on self-hosted runner'
description: 'Greet someone'
inputs:
  RITM:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
using: "composite"
  steps:
    - run: /Users/matteofoiadelli/Documents/Development/LiquibaseChangeLogGenerator/generateChangeLog.sh ${{ RITM }}
      shell: bash
