name: 'Check user permissions'
description: 'Checks whether the user who triggered the workflow has the privileges to do it.'
inputs:
    protectedEnvironments:
        description: "The list of environments for which to check the users permissions."
        required: true
        type: array
    
runs:
  using: "composite" 
  steps:
    - id: checkProtectedEnvironments
      if: !contains(fromJson(inputs.protectedEnvironments), github.event.repository.name)
      run: exit 0
      shell: bash
      
    - id: checkUser
      if: contains(fromJson(inputs.protectedEnvironments), github.event.repository.name) 
      shell: bash
      run: |
         echo "Checking user permission to perform the requested action on environment ${{ github.event.inputs.environment }}..."
         API_URL="https://api.github.com/repos/${{ github.repository }}/pulls?state=open&base=main"
         allowedUsers=($(curl -s -X GET -G -H 'authorization: Bearer ${{ github.token }}' $API_URL | grep -Eizo '"requested_reviewers": \[\s+({\s+(".+": "?.+"?,?\s+)+},?\s+)+\]' | grep -i -w login | tr -d ' ' | sed -E 's/"login":"(.+)",/\1/g' | sort -u))
         
         for allowedUser in ${allowedUsers[@]}
         do
          [[ ${{ github.actor }} == ${allowedUser} ]] && echo "...Permission granted!" && exit 0
         done
         
         echo "::error::...Permission denied! User ${{ github.actor }} cannot perform this action on environment ${{ github.events.inputs.environment }}. Insufficient privileges."
         exit 1
