name: Workflow that creates Liquibase changelog
on: 
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Environment to deploy to
        options: 
        - TEST
        - PROD
        required: true
      RITM:
        description: 'RITM name'     
        required: true
        type: string
      changelog-file:
        description: 'Liquibase changelog file to be executed'
        required: false
        type: string

jobs:
  create-changelog:
    name: Create Liquibase changelog
    runs-on: self-hosted
    outputs:
      changeLogFilePath: ${{ steps.generate-or-find-changelog-file.outputs.changeLogFilePath }}
      
    steps:
      - uses: actions/checkout@v1
      
      - name: Generate or find Liquibase changelog file
        id: generate-or-find-changelog-file
        uses: ./oracle_scripts_action
        with:
          RITM: ${{github.event.inputs.RITM}}
          environment: ${{github.event.inputs.environment}}
          changelog-file: ${{github.event.inputs.changelog-file}}
          
  process-changelog:
    name: Process Liquibase changelog
    runs-on: self-hosted
    needs: [ create-changelog ]
    
    steps:
      - name: Process changelog
        uses: liquibase/liquibase-github-action@v2
        with:
          operation: 'update'
          classpath: '/usr/local/opt/liquibase:/usr/local/opt/liquibase/lib/*'
          changeLogFile: ${{needs.create-changelog.outputs.changeLogFilePath}}
          username: 'ODI_MFOIADELLI'
          password: 'ODI_MFOIADELLI'
          url: 'jdbc:oracle:thin:@icteam-ora05:1521:ORA11G'
