name: ODI - Import Objects
on: 
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        required: true
        default: 'TEST'
      RITM:
        description: 'Directory of the RITM to be installed'     
        required: true
        type: string
      user:
        description: 'ODI connection user'
        type: choice
        default: 'ODI_MFOIADELLI'
        options:
          - ODI_MFOIADELLI
          - ODI_SCARRARA
        required: true

jobs:
  import-objects:
    name: Import ODI objects
    runs-on: self-hosted
    environment: ${{github.event.inputs.environment}}
    
    steps:
      - name: Code Checkout
        uses: actions/checkout@v3
      
      - name: Import ODI Objects
        id: generate-or-find-changelog-file
        uses: ./odi_actions/import_objects
        with:
          RITM: ${{github.event.inputs.RITM}}
          odiUrl: ${{ secrets.ODI_DB_URL }}
          odiSchema: ${{ secrets.ODI_DB_SCHEMA }}
          odiSchemaPwd: ${{ secrets.ODI_DB_SCHEMA_PASSWORD }}
          odiWorkRepository: ${{ secrets.ODI_WORK_REPOSITORY }}
          odiUsername: ${{ secrets.ODI_USER }}
          odiUserPwd: ${{ secrets.ODI_USER_PASSWORD }}
