name: Workflow that creates Liquibase changelog
on: 
  workflow_dispatch:
    inputs:
      RITM:
        description: 'RITM name'     
        required: true

jobs:
  build:
    name: Create Liquibase changelog
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v1
      - uses: ./self-hosted-runner-action-a
        with:
          RITM: ${{github.workspace}}"/OracleScripts/"${{github.event.inputs.RITM}}
