name: Workflow that creates Liquibase changelog
on: 
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Environment to deploy to
        options: 
        - TEST
        - PROD
        required: true
      RITM:
        description: 'RITM name'     
        required: true
        type: string
      changelogFile:
        description: 'Liquibase changelog file to be executed'
        required: false
        type: string

jobs:
  build:
    name: Create Liquibase changelog
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v1
      - if: "${{ github.event.inputs.changelogFile != '' }}"
        name: Find or create changelog file
        id: set-changelog-file-path
        run: |
          echo "${{github.event.inputs.changelogFile}}"
          ritmDir=$(find -E ${{ github.workspace }} -regex "${{ github.workspace }}/OracleScripts/[0-9]{6}/${{ github.event.inputs.RITM }}")
          echo "::set-output name=changelogFilePath::${ritmDir}/${{github.event.inputs.changelogFile}}"      
      - if: "${{ github.event.inputs.changelogFile == '' }}"
        name: Generate Liquibase changelog file
        id: generate-changelog-file
        uses: ./self-hosted-runner-action-a
        with:
          RITM: ${{github.event.inputs.RITM}}
          environment: ${{github.event.inputs.environment}}
      - name: Get changelog file
        run: |
          [[ -z ${{ steps.set-changelog-file-path.outputs.changelogFilePath }} ]] && file=${{ steps.generate-changelog-file.outputs.changelogFilePath }} || file=${{ steps.set-changelog-file-path.outputs.changelogFilePath }}
          echo "USING ${file} changelog for liquibase deploy"
