name: Runner From Secrets
on: 
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        required: true
        default: 'TEST'
      runner:
        type: choice
        description: Runner
        options:
        - runner-local-macbook
        - odi-runner
        
jobs:
  execute_step:
    environment: ${{github.event.inputs.environment}}
    name: ECHO TEST
    runs-on: ${{ join([${{github.event.inputs.runner}},${{github.event.inputs.environment}}], '_') }}
    steps:
      - name: echo
        id: echoTest
        run: |
          echo ${{github.event.inputs.runner}}
          
          error=0
          
          exit $error
