name: Runner From Secrets
on: 
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        required: true
        default: 'TEST'
      runner:
        type: choice
        description: Runner
        options:
        - runner-local-macbook
        - odi-runner

env:
  runner: fromJson('["${{github.event.inputs.environment}}", "${{github.event.inputs.runner}}"]')
jobs:
  execute_step:
    environment: ${{github.event.inputs.environment}}
    name: ECHO TEST
    runs-on: ${{github.event.inputs.runner}}
    steps:
      - name: echo
        id: echoTest
        run: |
          echo ${{github.event.inputs.runner}}
          echo ${{env.runner}}
          error=0
          
          exit $error
