name: Runner From Secrets
on: 
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        required: true
        default: 'TEST'
      runner:
        type: choice
        description: Runner
        options:
        - runner-local-macbook
        - odi-runner

env:
  runner: ${{ format('{0}_runner', github.event.inputs.environment) }}
jobs:
  execute_step:
    environment: ${{github.event.inputs.environment}}
    name: ECHO TEST
    runs-on: self-hosted
    steps:
      - name: echo
        id: echoTest
        run: |
          echo ${{github.event.inputs.runner}}
          echo "${{join(fromJSON(env.runner),'_')}}"
         
          error=0
          
          exit $error
