name: Runner From Secrets
on: 
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        required: true
        default: 'TEST'
      test:
        type: string
        required: true
env: 
  keyl: ${{ secrets.RUNNER_LABEL }}
  
jobs:
  execute_step:
    environment: ${{github.event.inputs.environment}}
    name: ECHO TEST
    runs-on: ${{ github.event.inputs.test }}
    steps:
      - name: echo
        id: echoTest
        run: |
          echo ${{github.event.inputs.test}}
          echo ${{ env.keyl }}
          
          error=0
          
          exit $error
