name: Validate Oracle Pull Request
on: 
  pull_request:
    branches:    
      - main
      
jobs:
  check-files-names:
    name: Check Files Names
    runs-on: self-hosted
    
    steps:
      - name: Check Names
        id: checkNames
        run: |
          URL="https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/files"
          FILES=$(curl -s -X GET -G $URL)
          echo ${FILES} | grep -e "*.(sql|plsql)"
          
