name: WINDOWS TEST
on: 
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        required: true
        default: 'TEST'

jobs:
  echoVars:
    runs-on: windows-latest
    environment: ${{ github.event.inputs.environment }}
    steps:
      - name: Set Env Variables From Secrets
        run: |
          # -------------------------------------------------------------------------
          # CONVERT GITHUB SECRETS CONTEXT TO PSObject 
          # HAVING EACH PROPERTY NAMED AFTER THE NAME OF THE CORRESPONDING SECRET
          # -------------------------------------------------------------------------
          $secretsObject='${{ toJSON(secrets) }}' | ConvertFrom-Json
          
          # -------------------------------------------------------------------------
          # LOOP THROUGH secretsObject PROPERTIES AND SET CORRESPONDING 
          # ENV VARIABLES AS <secretName>=<secretValue>
          # -------------------------------------------------------------------------
          $secretsObject.PSObject.Properties | foreach { 
            Set-Variable -Name $_.Name -Value $_.Value
          }
          
          $secretsObject.PSObject.Properties | foreach { 
            WRITE-HOST '$($_.Name): ' -NoNewline
            WRITE-HOST $($_.Value)
          }
        shell: pwsh
