name: WINDOWS TEST
on: 
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        required: true
        default: 'TEST'

jobs:
  echoVars:
    runs-on: windows-latest
    environment: ${{ github.event.inputs.environment }}
    steps:
      #- uses: actions/checkout@v3
      - name: Run echo secrets
        run: |
          $secretsObject='${{ toJSON(secrets) }}' | ConvertFrom-Json
          WRITE-HOST $secrets
          $secretsObject.PSObject.Properties | foreach { 
            Set-Variable -Name $_.Name -Value $_.Value
            WRITE-HOST $($_.Name)
            WRITE-HOST $($_.Value)
          }
        shell: pwsh
